### ISSUE TITLE
Users can view the portfolio owner's name on the navigation bar.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/portfolio-app#1]
# Motivation

Users should be able to clearly view the portfolio owner's name at the top of the page.

# Tasks

- [x] Configure linters.
- [x] Create an HTML index file.
- [x] Create a CSS stylesheet.
- [x] Import Bootstrap to preserve page order.
