### ISSUE TITLE
User can view the owner's resume.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/portfolio-app#11]
# Motivation

The portfolio should have a page that takes you to the owner's resume to convey qualifications and relevant work history information.

# Tasks

- [x] Implement Redux:
    - [x] Create a store to house state.
    - [x] Store the current view in state.
    - [x] Map state to components to render depending on the current view.
    - [x] Use the nav-link buttons to update the current view by dispatching an action.
- [x] Create a React component to display the resume:
    - [x] Load the resume as an image.
    - [x] Use a background image with a darkening layer for visual effect.
- [x] Add the Resume component to the list of components being rendered in app.js.
