### ISSUE TITLE
User can load a specific page of the site using a URL hash.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/portfolio-app#13]
# Motivation

Users should be able to load or reload the page at a specific hash to be taken to that specific view.

# Tasks

- [x] Handle hash changes:
    - [x] Add an event listener to the window to dispatch action on hash change.
- [x] Handle GET requests to specific hash URLs:
    - [x] Check window.location.hash on app component mount and set state if necessary.
