### ISSUE TITLE
User can visit the About page to get a brief summary of the owner.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/portfolio-app#15]
# Motivation

Users should be able to learn more about the owner of the portfolio at the About page.

# Tasks

- [x] Create a React component corresponding with the About page:
    - [x] Add a background image.
    - [x] Use a darkening div to make the section stand out from the background.
    - [x] Add an image for the About section.
    - [x] Add a text description.
    - [x] Organize accomplishments into a list.
