### ISSUE TITLE
User can visit the Contact page to get contact info or contact by form.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/portfolio-app#16]
# Motivation

Users should be able to contact the owner or get contact information via the Contact page of the site.

# Tasks

- [x] Create a React component corresponding with the Contact page:
    - [x] Use a background image with darkening layer for consistency.
    - [x] Use topic buttons to facilitate easy communication.
    - [x] Create a form for manual submissions:
        - [x] Create HTML elements for the form, textarea, and submit button.
        - [x] Set the value of the textarea from state with an onChange handler.
        - [x] Handle form submission.
    - [x] Link to LinkedIn and email address.
