### ISSUE TITLE
Visual update: Homepage.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/portfolio-app#20]
# Motivation

The homepage should provide users with a more memorable experience to improve the overall quality of the site.

# Tasks

- [x] Redesign the Home component:
    - [x] Add the portfolio owner name to the homepage above the social media buttons.
    - [x] Add a subtitle underneath the portfolio owner name corresponding to job title.
    - [x] Rename the portfolio owner name link on the navigation bar to "Home".
