### ISSUE TITLE
Visual update: Projects.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/portfolio-app#21]
# Motivation

The Projects page should have a more rich design to encourage users to click on a project.

# Tasks

- [x] Redesign the Projects component:
    - [x] Add styling to every other project for visual distinction:
        - [x] Darken the background color.
        - [x] Float the image to the right.
        - [x] Add a border to project demo divs.
