### ISSUE TITLE
Users can view links to social media profiles.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/portfolio-app#5]
# Motivation

Users should immediately see a splash image, with prominent social media buttons for linking to relavent profiles.

# Tasks

- [x] Create an Express server to host site:
    - [x] Install Express as a dependency.
    - [x] Create an index.js file.
    - [x] Create a public directory to be served as static middleware.
- [x] Create a file structure to separate server from client resources.
- [x] Add a splash image:
    - [x] Create a directory on the server to house image resources.
    - [x] Add image element to index.html.
    - [x] Style and position splash image.
    - [x] Darken image via overlapped transparent div.
- [x] Create social media links:
    - [x] Github.
    - [x] LinkedIn.
