### ISSUE TITLE
Users can see a project preview below the fold.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/portfolio-app#7]
# Motivation

Below the splash image and social media links, users should be able to get a small preview of each showcased project, with a small description and an image.

# Tasks

- [x] Create a template for preview projects including an image, title, description, and sub-description
- [x] Add a demo image for the template project to the images folder.
- [x] Use the Github description for project preview description.
- [x] Provide links to each app either hosted on Heroku or to the repository on Github.
