### ISSUE TITLE
Users can see previews for each project.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/portfolio-app#9]
# Motivation

Now that a template for project display has been developed, users should be able to see all projects to be showcased.

# Tasks

- [x] Implement Browserify:
    - [x] Install Browserify and Babelify as dependencies.
    - [x] Add an npm script to the package.json for "bundle".
    - [x] Add to the "watch" script to include bundling.
    - [x] Load bundled script in index.html.
- [x] Implement React:
    - [x] Install React as a dependency.
    - [x] Install styled components as a dependency.
    - [x] Create a React component for rendering the homepage display.
    - [x] Relocate all homepage HTML elements not including the nav-bar to the React component.
    - [x] Render projects from an object containing relevant project information.
    - [x] Use styled components to create components for each element in the project preview.
